# Generated by Django 3.2.5 on 2021-11-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dept',
            field=models.TextField(null=True),
        ),
    ]
