# Generated by Django 3.2.5 on 2021-12-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211128_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='founded',
            new_name='general',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='graduate_school',
            new_name='international',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='intern',
            new_name='scholarship',
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.TextField(null=True),
        ),
    ]
